version: '3.9'
services:
  app:
    build:
      context: ./
      dockerfile: docker/Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www
    volumes:
      - ./:/var/www

  nginx:
    image: nginx:1.23.3-alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d