<?php

declare(strict_types=1);


require __DIR__ . '/../vendor/autoload.php';

//can also extend other classes and implement interfaces and use traits
//name gets generated by engine
//Type Hinting is only available with 'object' because the class doesn't have a defined name
//type hinting with interfaces does work

//good for testing

$a = new \App\ClassA(1, 2);



var_dump($a->bar());